In [1]:
import numpy as np

a=np.array([1,2,3,4])

In [2]:
a


array([1, 2, 3, 4])

In [7]:
type(a)


numpy.ndarray

In [11]:
b=np.array([[1,2,3,4],[4,3,2,1]])

In [13]:
b

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [15]:
c=np.zeros((5,5))

In [18]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
d=np.full((3,2),56)

In [24]:
d


array([[56, 56],
       [56, 56],
       [56, 56]])

In [26]:
n1=np.arange(10,20)

In [28]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
n2=np.arange(10,50,5)

In [33]:
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [35]:
n4=np.arange(50,101)

In [39]:
n4

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [44]:
n5=np.random.randint(1,10000,10)

In [45]:
n5

array([9056, 7997, 5203, 5062, 5967, 2942, 2962, 9357, 3550, 6682])

In [49]:
n6=np.array([[1,2,3,4],[4,5,6,7]])
n6

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [55]:
n6.shape=(4,2)
n6

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [58]:
#vertical stack
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))


array([[10, 20, 30],
       [40, 50, 60]])

In [59]:
#horizontal stack

n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [61]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])


In [63]:
np.intersect1d(n1,n2)

array([50, 60])

In [66]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [68]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [70]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.sum([n1,n2]) 

210

In [72]:
np.sum([n1,n2],axis=0) # based on column wise addition

array([50, 70, 90])

In [75]:
np.sum([n1,n2],axis=1) # based on row wise addition

array([ 60, 150])

In [76]:
n1=np.array([10,20,30])

In [77]:
n1

array([10, 20, 30])

In [78]:
n1+5

array([15, 25, 35])

In [79]:
n1-5

array([ 5, 15, 25])

In [81]:
n1*10

array([100, 200, 300])

In [82]:
n1/5

array([2., 4., 6.])

In [83]:
n1=np.array([10,20,30,40,50,60])

In [85]:
n1

array([10, 20, 30, 40, 50, 60])

In [87]:
np.mean(n1)

35.0

In [89]:
np.median(n1)

35.0

In [92]:
np.std(n1)

17.07825127659933

In [93]:
np.save('my_numpy',n1)

In [94]:
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])